/**
 * Generates embed snippets and standalone HTML exports from a BotConfig.
 */
export class EmbedCodeGenerator {
  /** @param {import("../models/BotConfig.js").BotConfig} config */
  generateSnippet(config) {
    const indent = (s, n = 4) => s.split("\n").map(l => " ".repeat(n) + l).join("\n");
    const chips  = JSON.stringify(config.activeChips, null, 2);
    const qa     = JSON.stringify(
      config.qaItems.filter(e => e.isValid()).map(e => ({ q: e.q, a: e.a })),
      null, 2
    );

    return [
      `<!-- ${config.botName} AI Chatbot — generated by Javadov -->`,
      `<script src="https://cdn.botforge.io/v1.js"><\/script>`,
      `<script>`,
      `  BotForge.init({`,
      `    name:          "${config.botName}",`,
      `    company:       "${config.company}",`,
      `    avatar:        "${config.avatar}",`,
      `    primaryColor:  "${config.primaryColor}",`,
      `    userColor:     "${config.userColor}",`,
      `    borderRadius:  ${config.chatRadius},`,
      `    tone:          "${config.tone}",`,
      `    position:      "${config.position}",`,
      `    welcomeMsg:    ${JSON.stringify(config.welcomeMsg)},`,
      `    chips:  ${indent(chips, 12).trimStart()},`,
      `    qa:     ${indent(qa, 12).trimStart()},`,
      `  });`,
      `<\/script>`,
    ].join("\n");
  }

  generateStandaloneHTML(config) {
    const qa    = JSON.stringify(config.qaItems.filter(e => e.isValid()).map(e => ({ q: e.q, a: e.a })));
    const chips = JSON.stringify(config.activeChips);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${config.botName} - Chat Support</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: sans-serif; }
    #bf-toggle {
      position: fixed; bottom: 24px; right: 24px;
      width: 56px; height: 56px; border-radius: 50%;
      background: ${config.primaryColor}; color: #fff;
      border: none; font-size: 26px; cursor: pointer;
      box-shadow: 0 4px 16px rgba(0,0,0,0.2); z-index: 999;
      transition: transform 0.2s;
    }
    #bf-toggle:hover { transform: scale(1.08); }
    #bf-window {
      position: fixed; bottom: 92px; right: 24px;
      width: 340px; height: 500px; border-radius: ${config.chatRadius}px;
      background: #fff; box-shadow: 0 8px 40px rgba(0,0,0,0.18);
      display: flex; flex-direction: column; overflow: hidden;
      z-index: 998; border: 1px solid rgba(0,0,0,0.08);
      transition: opacity 0.2s, transform 0.2s;
    }
    #bf-window.hidden { opacity: 0; pointer-events: none; transform: translateY(12px); }
    #bf-header {
      background: ${config.primaryColor}; padding: 14px 16px;
      display: flex; align-items: center; gap: 10px; flex-shrink: 0;
    }
    #bf-avatar {
      width: 34px; height: 34px; border-radius: 50%;
      background: rgba(255,255,255,0.2);
      display: flex; align-items: center; justify-content: center; font-size: 18px;
    }
    #bf-name { font-size: 14px; font-weight: 600; color: #fff; }
    #bf-status { font-size: 11px; color: rgba(255,255,255,0.75); margin-top: 1px; }
    #bf-messages {
      flex: 1; overflow-y: auto; padding: 12px;
      display: flex; flex-direction: column; gap: 8px;
    }
    .bf-msg { max-width: 80%; display: flex; flex-direction: column; gap: 3px; }
    .bf-msg.bot { align-self: flex-start; }
    .bf-msg.user { align-self: flex-end; }
    .bf-bubble { padding: 9px 13px; font-size: 13px; line-height: 1.5; border-radius: 16px; }
    .bf-msg.bot .bf-bubble {
      background: #f4f4f8; color: #111;
      border-bottom-left-radius: 3px; border: 1px solid rgba(0,0,0,0.07);
    }
    .bf-msg.user .bf-bubble {
      background: ${config.userColor}; color: #fff; border-bottom-right-radius: 3px;
    }
    .bf-time { font-size: 10px; color: #aaa; padding: 0 4px; }
    .bf-msg.user .bf-time { text-align: right; }
    #bf-chips {
      display: flex; gap: 6px; flex-wrap: wrap;
      padding: 6px 10px; border-top: 1px solid rgba(0,0,0,0.07);
    }
    .bf-chip {
      padding: 4px 10px; border-radius: 20px; font-size: 11px; cursor: pointer;
      border: 1px solid ${config.primaryColor}; color: ${config.primaryColor};
      background: transparent; font-family: sans-serif;
    }
    .bf-chip:hover { background: ${config.primaryColor}; color: #fff; }
    #bf-input-row {
      padding: 9px 10px; border-top: 1px solid rgba(0,0,0,0.08);
      display: flex; gap: 7px; flex-shrink: 0;
    }
    #bf-input {
      flex: 1; padding: 8px 13px; border-radius: 20px;
      border: 1px solid rgba(0,0,0,0.14); font-size: 13px;
      font-family: sans-serif; outline: none;
    }
    #bf-send {
      width: 34px; height: 34px; border-radius: 50%;
      background: ${config.primaryColor}; border: none;
      color: #fff; font-size: 14px; cursor: pointer; flex-shrink: 0;
    }
    .bf-typing {
      display: flex; gap: 4px; align-items: center; padding: 10px 13px;
      background: #f4f4f8; border-radius: 16px; border-bottom-left-radius: 3px;
      width: fit-content; border: 1px solid rgba(0,0,0,0.07);
    }
    .bf-dot { width: 7px; height: 7px; border-radius: 50%; background: #aaa; animation: bfdot 1.1s infinite; }
    .bf-dot:nth-child(2) { animation-delay: .18s; }
    .bf-dot:nth-child(3) { animation-delay: .36s; }
    @keyframes bfdot { 0%,60%,100%{transform:translateY(0)} 30%{transform:translateY(-5px)} }
  </style>
</head>
<body>

<button id="bf-toggle">💬</button>

<div id="bf-window" class="hidden">
  <div id="bf-header">
    <div id="bf-avatar">${config.avatar}</div>
    <div>
      <div id="bf-name">${config.botName}</div>
      <div id="bf-status">● Online · Replies instantly</div>
    </div>
  </div>
  <div id="bf-messages"></div>
  <div id="bf-chips"></div>
  <div id="bf-input-row">
    <input id="bf-input" placeholder="Type a message…"/>
    <button id="bf-send">➤</button>
  </div>
</div>

<script>
const CONFIG = {
  botName:         ${JSON.stringify(config.botName)},
  company:         ${JSON.stringify(config.company)},
  avatar:          ${JSON.stringify(config.avatar)},
  welcomeMsg:      ${JSON.stringify(config.welcomeMsg)},
  fallbackMsg:     ${JSON.stringify(config.fallbackMsg)},
  tone:            ${JSON.stringify(config.tone)},
  personalityNote: ${JSON.stringify(config.personalityNote)},
  bizContext:      ${JSON.stringify(config.bizContext)},
  qa:              ${qa},
  chips:           ${chips},
  apiKey:          "YOUR_GROQ_API_KEY_HERE",
  model:           "llama-3.3-70b-versatile",
};

let history  = [];
let isTyping = false;

const win     = document.getElementById("bf-window");
const toggle  = document.getElementById("bf-toggle");
const msgs    = document.getElementById("bf-messages");
const input   = document.getElementById("bf-input");
const send    = document.getElementById("bf-send");
const chipsEl = document.getElementById("bf-chips");

toggle.onclick = () => win.classList.toggle("hidden");

CONFIG.chips.slice(0, 3).forEach(chip => {
  const btn = document.createElement("button");
  btn.className   = "bf-chip";
  btn.textContent = chip;
  btn.onclick     = () => sendMessage(chip);
  chipsEl.appendChild(btn);
});

addMessage("bot", CONFIG.welcomeMsg);

function now() {
  return new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

function addMessage(role, text) {
  const div = document.createElement("div");
  div.className = "bf-msg " + role;
  div.innerHTML = \`<div class="bf-bubble">\${text}</div><div class="bf-time">\${now()}</div>\`;
  msgs.appendChild(div);
  msgs.scrollTop = msgs.scrollHeight;
}

function showTyping() {
  const el = document.createElement("div");
  el.id        = "bf-typing";
  el.className = "bf-typing";
  el.innerHTML = '<div class="bf-dot"></div><div class="bf-dot"></div><div class="bf-dot"></div>';
  msgs.appendChild(el);
  msgs.scrollTop = msgs.scrollHeight;
  return el;
}

function buildSystemPrompt() {
  const toneMap = {
    friendly:     "warm and friendly",
    professional: "professional and formal",
    playful:      "playful and fun",
    concise:      "very concise, max 2 sentences",
  };
  const qaBlock = CONFIG.qa.map(e => \`Q: \${e.q}\\nA: \${e.a}\`).join("\\n\\n");
  let prompt = \`You are \${CONFIG.botName}, a customer support AI for \${CONFIG.company}. Be \${toneMap[CONFIG.tone] || "helpful"}.\`;
  if (CONFIG.bizContext)      prompt += \`\\nBusiness info: \${CONFIG.bizContext}\`;
  if (qaBlock)                prompt += \`\\nKnowledge base:\\n\${qaBlock}\`;
  if (CONFIG.personalityNote) prompt += \`\\nInstructions: \${CONFIG.personalityNote}\`;
  prompt += \`\\nFallback: "\${CONFIG.fallbackMsg}"\\nKeep replies to 1-3 sentences.\`;
  return prompt;
}

async function sendMessage(text) {
  if (!text.trim() || isTyping) return;
  input.value = "";
  addMessage("user", text);
  history.push({ role: "user", content: text });
  isTyping = true;
  const typingEl = showTyping();

  try {
    const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": "Bearer " + CONFIG.apiKey,
      },
      body: JSON.stringify({
        model:      CONFIG.model,
        max_tokens: 300,
        messages:   [{ role: "system", content: buildSystemPrompt() }, ...history],
      }),
    });
    const data  = await res.json();
    const reply = data.choices?.[0]?.message?.content || CONFIG.fallbackMsg;
    history.push({ role: "assistant", content: reply });
    typingEl.remove();
    addMessage("bot", reply);
  } catch {
    typingEl.remove();
    addMessage("bot", CONFIG.fallbackMsg);
  } finally {
    isTyping = false;
  }
}

send.onclick          = () => sendMessage(input.value);
input.onkeydown       = e => { if (e.key === "Enter") sendMessage(input.value); };
<\/script>
</body>
</html>`;
  }

  buildPitchPrompt(config) {
    return (
      `Write a freelance sales pitch and pricing guide for an AI chatbot called "${config.botName}" ` +
      `built for "${config.company}". Include three pricing tiers, objection handling, ` +
      `and a cold email template I can send to potential clients.`
    );
  }
}

export const embedCodeGenerator = new EmbedCodeGenerator();